// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5rdLm-fSjujh2iUf1PHRIw7eBwcQAhpc',
    appId: '1:456581821334:web:47da44bec93a415b6c23b7',
    messagingSenderId: '456581821334',
    projectId: 'super-app-627f5',
    authDomain: 'super-app-627f5.firebaseapp.com',
    storageBucket: 'super-app-627f5.appspot.com',
    measurementId: 'G-8Q38XNWJPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZKLmFZNSwS5WIxaRdE20V3_vizY1-YGc',
    appId: '1:456581821334:android:0168a0f32adaf6a26c23b7',
    messagingSenderId: '456581821334',
    projectId: 'super-app-627f5',
    storageBucket: 'super-app-627f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8F0Krdp3-WSN_NwYAoa2KBLXoMPnBkWo',
    appId: '1:456581821334:ios:f1e16a32009dda616c23b7',
    messagingSenderId: '456581821334',
    projectId: 'super-app-627f5',
    storageBucket: 'super-app-627f5.appspot.com',
    iosClientId: '456581821334-uc168dari9tecpe5sd2m2fpijieam612.apps.googleusercontent.com',
    iosBundleId: 'com.example.spd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8F0Krdp3-WSN_NwYAoa2KBLXoMPnBkWo',
    appId: '1:456581821334:ios:f1e16a32009dda616c23b7',
    messagingSenderId: '456581821334',
    projectId: 'super-app-627f5',
    storageBucket: 'super-app-627f5.appspot.com',
    iosClientId: '456581821334-uc168dari9tecpe5sd2m2fpijieam612.apps.googleusercontent.com',
    iosBundleId: 'com.example.spd',
  );
}
